---
name: PR Lint

on:
  push:
    branches-ignore: [master, main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master, main]

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  SuperLinter:
    uses: ivuorinen/actions/pr-lint@625c37446b1c7e219755a40807f825c9283f6e05 # 25.7.7
